### ISSUE TITLE
Question about 2 failures when running pytest

### ISSUE THREAD

**Issue by ValescaHarezlak** [ibs-pan/foodwebviz#12]
Hi,

Wanted to get familiarized with the package, but after installing, 2 fails are found when running pytest.  (FYI I use Python 3.9.16).
First fail is on test-get-normalized-flows (see attachment 'first fail') and the second fail is on the thest_write_scor but seems to be related to reading the scor file (see the two attachments on 'second fail). Probably I've done something wrong during installation, but I've no clue where to search and maybe for you it is a known failure. 

Thanks!
Valesca
![first fail](https://user-images.githubusercontent.com/118539949/234270093-00596441-7050-4a5f-aa7c-6033d5b16cd8.jpg)
![second fail part one](https://user-images.githubusercontent.com/118539949/234270099-d1e2b21a-ba31-49cb-81d6-f4328b32c072.jpg)
![second fail part two](https://user-images.githubusercontent.com/118539949/234270103-93d0cdf8-37b4-4ad2-8eb2-525d564cf343.jpg)

**Comment by mkjiskrz** [comment]
Dear @ValescaHarezlak, thank you for posting the issue! 
We have been altering the SCOR input convention a bit, I will review it and the tests. My expectation is that either we forgot to update the tests, or it is a minor issue, so feel free to use the other functionalities which used to work correctly last time we've been using the package.

**Comment by mkjiskrz** [comment]
Dear @ValescaHarezlak, thank you for flagging the issues, we have resolved them. They concerned reading/writing from SCOR files and TST normalisation of heatmaps.
Apparently pandas' to_csv() method seems to have troubles on Windows - extra empty lines are added. There were also some typos and mistakes that led to problems with normalisation/normalization, tst/TST. Now the code works and should also be more robust.

**Comment by ValescaHarezlak** [comment]
Wonderful! Thanks for fixing this problem so swiftly! Looking forward to play around with this package.
